<?php

    /*
    
        localhost Ltd - ALPHA CMS
        
        Version: 11.0
        
        File name: admin.phtml
        Description: This file contains the admin HTML.
        
        Coded by George Delaportas (G0D)
        
        localhost Ltd
        Copyright (c) 2014
    
    */
    
    
    
    ALPHA_CMS::Load_Extension('login_form', 'php');
    
    
    
    /* ---------- End ---------- */

?>
