<?php

    /*
    
        localhost Ltd - ALPHA CMS
        
        Version: 11.0
        
        File name: admin_dashboard.phtml
        Description: This file contains the admin dashboard HTML.
        
        Coded by George Delaportas (G0D)
        
        localhost Ltd
        Copyright (c) 2014
    
    */
    
    
    
    $my_lang = ALPHA_CMS::Get_Language();
    
    echo ALPHA_CMS::Load_Content('dashboard_content', 'content', $my_lang);

?>



    <div id="dynamic_pane" class="class_content_area">
    <?php
    
        ALPHA_CMS::Load_Extension('wasp', 'js');
        ALPHA_CMS::Load_Extension('nature', 'js');
        ALPHA_CMS::Load_Extension('content_fetcher', 'ajax');
    
    ?>
    </div>
    
    <script type="text/javascript">
    
        // Set sigma layer to screen
        function Set_Sigma_Layer()
        {
        
            var dynamic_object = null;
            
            dynamic_object = document.createElement('div');
            
            dynamic_object.setAttribute('id', 'sigma_layer');
            dynamic_object.setAttribute('style', 'display: none; position: absolute;');
            
            document.body.appendChild(dynamic_object);
            
            document.getElementById('sigma_layer').style.width = '880px';
            
            document.getElementById('sigma_layer').style.left = (document.body.clientWidth / 2) - 
            (Get_Value(document.getElementById('sigma_layer').style.width) / 2) + 8 + 'px';
            
            return 1;
        
        }
        
        Set_Sigma_Layer();
        
        WASP_Setup_Element('dynamic_pane', 'obj_1', 'Info label', 'Test window with automatic defolding...', 
                           '<div style="font-size: medium; padding: 4px;">This is a test content.<br></div>', 
                           'This is a TEST status message that goes on...',
                           (document.body.clientWidth / 2) - 130, (screen.height / 2) + 150, 260, 200, 'block', 
                           1, 0.5, 100, 30, Get_Value(document.getElementById('sigma_layer').style.left) - 2, 315, 
                           Get_Value(document.getElementById('sigma_layer').style.left) + 
                           Get_Value(document.getElementById('sigma_layer').style.width), 1140);
        
        WASP_Init();
        
        Nature_Init('default');
        
        //AJAX_Fetch_Content('obj_1_data', '', 1, 1);
    
    </script>



<?php /* ---------- End ---------- */ ?>
