<?php

    /*
    
        localhost Ltd - ALPHA CMS
        
        File name: features_security.phtml
        Description: This file contains the features security view.
    
    */

?>



    <div id="main_content">
        <?php echo ALPHA_CMS::Load_Content('security', 'content', ALPHA_CMS::Get_Language()); ?>
    </div>

    <div id="sidebar">
        <?php
        
            $parent_menu = MVC_Menu::Get_Parent_Menu();
            
            $mvc_menu = MVC_Menu::Show($parent_menu, 0, ALPHA_CMS::Get_Language());
            
            echo '<h3>' . ALPHA_CMS::Load_Content('features', 'content', ALPHA_CMS::Get_Language()) . '</h3>';
            echo $mvc_menu;
        
        ?>
    </div>



<?php /* ---------- End ---------- */ ?>
