<?php

    /*
    
        localhost Ltd - ALPHA CMS
        
        Version: 11.0
        
        File name: home.phtml
        Description: This file contains the home view.
        
        Coded by George Delaportas (G0D)
        
        localhost Ltd
        Copyright (c) 2014
    
    */

?>



    <div id="main_content">
        <?php echo ALPHA_CMS::MVC_Show_Content('home-content'); ?>
    </div>

    <div id="sidebar">
        <?php echo ALPHA_CMS::MVC_Show_Content('key_features'); ?>
    </div>



<?php /* ---------- End ---------- */ ?>
