<?php

    /*
    
        localhost Ltd - ALPHA CMS
        
        Version: 11.0
        
        File name: root.phtml
        Description: This file contains the root view.
        
        Coded by George Delaportas (G0D)
        
        localhost Ltd
        Copyright (c) 2014
    
    */

?>



    <div id="main_content">
        <?php echo ALPHA_CMS::MVC_Show_Content(''); ?>
    </div>



<?php /* ---------- End ---------- */ ?>
